### ISSUE TITLE
'PDIR' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by amitleuva1987** [millsp/prisma-nextjs-serverlessnextjs#2]
I am using next js ( version - '12.1.6'. ). I use Prisma ORM with mysql database hosted over railway.app. I was looking out for a serverless solution  which works with nextjs and prisma. I came across this repository but when I use your .yml file, I get below error. am I missing something or what?

```
'PDIR' is not recognized as an internal or external command,
operable program or batch file.

  error:
  Error: Command failed: PDIR=node_modules/.prisma/client/; LDIR=.serverless_nextjs/api-lambda/; if [ "$(ls -A $LDIR)" ]; then mkdir -p $LDIR$PDIR; cp "$PDIR"query-engine-rhel-* $LDIR$PDIR; cp "$PDIR"schema.prisma $LDIR$PDIR; fi;
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at NextjsComponent.postBuild (C:\Users\Avita\.serverless\components\registry\npm\@sls-next\serverless-component@3.7.0\node_modules\@sls-next\serverless-component\dist\component.js:173:42)
    at NextjsComponent.default (C:\Users\Avita\.serverless\components\registry\npm\@sls-next\serverless-component@3.7.0\node_modules\@sls-next\serverless-component\dist\component.js:23:18)
    at async fn (C:\Users\Avita\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\template\utils.js:280:41)        
    at async Promise.all (index 0)
    at async executeGraph (C:\Users\Avita\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\template\utils.js:294:3)
    at async Template.default (C:\Users\Avita\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\template\serverless.js:67:38)
    at async Object.runComponents (C:\Users\Avita\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\cli\src\index.js:222:17) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7188,
  stdout: null,
  stderr: null
}
```

belos is my serverless.yml

```
myNextApp:
  component: "@sls-next/serverless-component"
  inputs:
    minifyHandlers: true
    build:
      postBuildCommands:
        - PDIR=node_modules/.prisma/client/;
          LDIR=.serverless_nextjs/api-lambda/;
          if [ "$(ls -A $LDIR)" ]; then
            mkdir -p $LDIR$PDIR;
            cp "$PDIR"query-engine-rhel-* $LDIR$PDIR;
            cp "$PDIR"schema.prisma $LDIR$PDIR;
          fi;
        - PDIR=node_modules/.prisma/client/;
          LDIR=.serverless_nextjs/default-lambda/;
            if [ "$(ls -A $LDIR)" ]; then
              mkdir -p $LDIR$PDIR;
              cp "$PDIR"query-engine-rhel-* $LDIR$PDIR;
              cp "$PDIR"schema.prisma $LDIR$PDIR;
          fi;
```

also, I would appreciate if anybody has the latest solution of making prisma work with next js serverless. 

Thank You

**Comment by amitleuva1987** [comment]
postbuildCommands doesn't require anymore. I mean, in the newer versions of next and prisma. It just requires useServerlessTraceTarget: true under inputs section in serverless.yml like . this is the [url](https://github.com/serverless-nextjs/serverless-next.js/issues/2459) for detailed solution. 

```
inputs:
     useServerlessTraceTarget: true
```

moreover, above postbuildCommands will not work with windows. for windows, you have to do something like below

```
inputs:
  minifyHandlers: true
  build:
     postBuildCommands:
         set PDIR=node_modules\.prisma\client\
         set LDIR=.serverless_nextjs\api-lambda\
         set DDIR=.serverless_nextjs\default-lambda\
         if exist %LDIR% (
         md %LDIR%%PDIR%
         copy %PDIR%* %LDIR%%PDIR%
         md %DDIR%%PDIR%
         copy %PDIR%* %DDIR%%PDIR%

```
